make summary steps have proper result types

diff --git a/.github/workflows/test-lint.yml b/.github/workflows/test-lint.yml
--- a/.github/workflows/test-lint.yml
+++ b/.github/workflows/test-lint.yml
@@ -58,11 +58,18 @@ jobs:
   summary:
     name: Summary (lint)
     runs-on: ubuntu-latest
-    if: always()
     timeout-minutes: 1
     needs:
       - enforce-changeset
       - lint
     steps:
       - name: Check All
-        run: echo OK
+        run: |-
+          for status in ${{ join(needs.*.result, ' ') }}
+          do
+            if [ "$status" != "success" ] && [ "$status" != "skipped" ]
+            then
+              echo "Some checks failed"
+              exit 1
+            fi
+          done
