Fix it

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -104,7 +104,12 @@ jobs:
     runs-on: ubuntu-latest
     name: Conclusion
     steps:
-      - run: exit 0
-        if: success()
-      - run: exit 1
-        if: failure()
+      - run: |-
+          for status in ${{ join(needs.*.result, ' ') }}
+          do
+            if [ "$status" != "success" ] && [ "$status" != "skipped" ]
+            then
+              echo "Some checks failed"
+              exit 1
+            fi
+          done
